server:
  port: 20001
spring:
  application:
    name: mi-ocr-gateway
  redis:
    host: 47.94.107.244
    port: 6379
    password: 123456
    timeout: 12000
    jedis:
      pool:
        max-active: 1024
        max-idle: 128
eureka:
  instance:
    virtual-host-name: mi-ocr-gateway
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
zuul:
  thread-pool:
    use-separate-thread-pools: true
  routes:
    mi-ocr-web-captcha-service:
      path: /captcha-api/**
    mi-ocr-web-user-service:
      path: /user-api/**
    mi-ocr-web-order-service:
      path: /order-api/**
  ratelimit:
    enabled: true
    behind-proxy: true
    policy-list:
      mi-ocr-web-captcha-service:
        - limit: 3000
          quota: 30
          refresh-interval: 1
          type:
            - user
            - origin
            - url
    #repository: REDIS
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
